### ISSUE TITLE
Bug: minSdkVersion should be 21 and not 14

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [whyorean/Authenticator#1]
Sadly there is no documentation whether this repository is a sample or a library, and how to use it (sadly no docs at all), but it seems this repository uses stuff from API 21 and not from API 14 as it says:

![image](https://user-images.githubusercontent.com/5357526/108913200-5287b580-7632-11eb-9364-1d506542f32e.png)

Is it ok to copy this code and modify as we wish? It doesn't show a license either?

**Comment by whyorean** [comment]
Bumped up minSDK to 19

**Comment by AndroidDeveloperLB** [comment]
But it said it requires 21...
